export const pageStyles = {
  container: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    color: '#f9fafb',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    overflow: 'hidden',
  },
  video: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    objectFit: 'cover',
    zIndex: -1,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'linear-gradient(to bottom, rgba(11, 14, 19, 0.4), rgba(11, 14, 19, 0.8))',
    zIndex: 0,
    pointerEvents: 'none'
  },
  logo: {
    position: 'absolute',
    top: '1.25rem',
    left: '1.5rem',
    fontSize: '1.8rem',
    fontWeight: 900,
    letterSpacing: '0.2em',
    fontFamily: "'Inter', sans-serif",
    textTransform: 'uppercase',
    background: 'linear-gradient(135deg, #fff 0%, #94a3b8 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    filter: 'drop-shadow(0 4px 6px rgba(0,0,0,0.3))',
    zIndex: 10
  },
  contentWrapper: {
    position: 'relative',
    zIndex: 1,
    width: '100vw',
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.5rem',
    background: 'transparent',
    overflow: 'hidden',
  },
  card: {
    width: '100%',
    maxWidth: 360,
    padding: '1.5rem 2rem',
    borderRadius: '1.5rem',
    background: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(24px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.25rem',
  },
  title: {
    fontSize: '1.4rem',
    fontWeight: 800,
    marginBottom: '0.4rem',
    color: '#fff',
    lineHeight: '1.2',
  },
  subtitle: {
    fontSize: '0.85rem',
    color: '#94a3b8',
    lineHeight: '1.4',
    margin: 0,
  },
  optionsContainer: {
    marginBottom: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px'
  },
  option: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.6rem 0.8rem',
    cursor: 'pointer',
    borderRadius: '0.8rem',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    transition: 'all 0.2s ease',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  radioInput: {
    width: '1.25rem',
    height: '1.25rem',
    borderRadius: '50%',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    marginRight: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  radioInner: {
    width: '0.6rem',
    height: '0.6rem',
    borderRadius: '50%',
    backgroundColor: '#fff',
  },
  checkboxInput: {
    width: '1.25rem',
    height: '1.25rem',
    borderRadius: '0.4rem',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    marginRight: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  optionText: {
    fontSize: '0.95rem',
    color: '#e2e8f0',
  },
  buttonContainer: {
    display: 'flex',
    gap: '1.25rem',
    justifyContent: 'stretch',
  },
  backButton: {
    flex: 1,
    padding: '0.75rem',
    borderRadius: '1.2rem',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#94a3b8',
    fontWeight: 600,
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  nextButton: {
    flex: 2,
    padding: '0.75rem',
    borderRadius: '1.2rem',
    border: 'none',
    fontWeight: 700,
    fontSize: '1.1rem',
    color: '#fff',
    transition: 'all 0.3s ease',
  },
}

export const buttonStates = {
  enabled: {
    background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
    cursor: 'pointer',
    boxShadow: '0 4px 15px rgba(34, 197, 94, 0.3)',
    opacity: 1,
  },
  disabled: {
    background: 'rgba(255, 255, 255, 0.05)',
    cursor: 'not-allowed',
    boxShadow: 'none',
    opacity: 0.5,
    color: '#64748b'
  },
  hover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 8px 25px rgba(34, 197, 94, 0.5)',
  },
  backHover: {
    color: '#fff',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
}

export const optionStates = {
  selected: {
    fontWeight: 700,
    color: '#fff',
    borderColor: 'rgba(34, 197, 94, 0.4)',
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
  },
  unselected: {
    fontWeight: 400,
  },
  hover: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
}

